### ISSUE TITLE
How can I save two videos in single file ?

### ISSUE THREAD

**Issue by pranitshirsath** [anibalbastiass/android.vuro.dualcamera#4]
e.g. both the videos from front and rear camera should be display in single video file instead of creating two separate files.

can you please suggest anything, please help me out

**Comment by anibalbastiass** [comment]
Hey @pranitshirsath. Honestly, it's not simple and straightforward to do that on Android. 

However, you can use the [FFMPEG library](https://github.com/tanersener/mobile-ffmpeg) to join both videos and generate a single one. It takes processing time, where I recommend you to use a Service or WorkManager while this video is generated in real time in your Android app.

I hope that is your help. Greetings.

**Comment by pranitshirsath** [comment]
> Hey @pranitshirsath. Honestly, it's not simple and straightforward to do that on Android.

Thanks for your reply @anibalbastiass but I want to record the video of front camera and back camera simultaneously not after one another means basically front camera video will display on top and back camera video will display below that like this below app link https://play.google.com/store/apps/details?id=com.app.dualcam.

 so can you please suggest me anything regarding this like how can we achieve this
